service: nest-lambda-deepl

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  httpApi:
    cors: true
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  main:
    handler: slsdist/index.handler
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: '{proxy+}'

package:
  patterns:
    - '!src/**'
    - '!test/**'
    - '!dist/**'
    - '!node_modules/**'
    - 'slsdist'
